### ISSUE TITLE
R version requirement

### ISSUE THREAD

**Issue by kylebmetrum** [dpastoor/satchel#2]
Any way to relax this for a friend?  Not sure if there is a real requirement or you're just trying to stay current.

```r
ERROR: this R is version 3.2.3, package 'satchel' requires R >= 3.3.0
```

**Comment by dpastoor** [comment]
nope no real requirement

**Comment by dpastoor** [comment]
done in 8f3787de8952fff4b0249b64d40b9a520af2d9eb

**Comment by kylebmetrum** [comment]
Thanks.  In case it wasn't clear ... asked for this to accommodate a platform where I can't switch to 3.3.
